openapi: 3.0.3
info:
  title: Todo Search API
  description: Full-text search API for tasks
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development
  - url: https://api.todo-app.example.com
    description: Production

paths:
  /api/{user_id}/tasks/search:
    get:
      summary: Search tasks
      description: Full-text search across task titles and descriptions
      operationId: searchTasks
      tags:
        - Search
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID (must match authenticated user)
        - name: q
          in: query
          required: true
          schema:
            type: string
            minLength: 1
          description: Search query (keywords)
          example: "meeting project"
        - name: priority
          in: query
          schema:
            type: string
            enum: [high, medium, low]
          description: Filter results by priority
        - name: tags
          in: query
          schema:
            type: string
          description: Filter results by tags (comma-separated)
          example: "work,urgent"
        - name: status
          in: query
          schema:
            type: string
            enum: [all, pending, completed]
            default: all
          description: Filter by completion status
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Maximum number of results
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/TaskSearchResult'
                  total:
                    type: integer
                    description: Total number of matching tasks
                    example: 15
                  query:
                    type: string
                    description: Original search query
                    example: "meeting project"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TaskSearchResult:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - priority
        - tags
        - created_at
        - relevance
      properties:
        id:
          type: integer
          example: 123
        user_id:
          type: string
          format: uuid
        title:
          type: string
          example: "Project meeting notes"
        description:
          type: string
          nullable: true
          example: "Discuss project timeline and deliverables"
        completed:
          type: boolean
          example: false
        due_date:
          type: string
          format: date-time
          nullable: true
        priority:
          type: string
          enum: [high, medium, low]
          example: "high"
        tags:
          type: array
          items:
            type: string
          example: ["work", "meeting"]
        is_recurring:
          type: boolean
          example: false
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        relevance:
          type: number
          format: float
          description: Search relevance score (higher = more relevant)
          example: 0.85

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Search query is required"
    Unauthorized:
      description: Missing or invalid authentication
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Not authenticated"
